//! Benchmarks comparing Blindplane's cryptographic core against established
//! implementations on the same machine, in the same process, on the same data.
//!
//! Methodology, so the numbers mean something:
//!
//! - each measurement runs for at least 250 ms, and the reported figure is the
//!   best of five such rounds, which suppresses scheduler noise without
//!   flattering any single implementation;
//! - every implementation processes identical inputs and its output is checked,
//!   so a fast wrong answer cannot win;
//! - throughput counts plaintext bytes, not ciphertext, so the tag does not
//!   inflate anyone's number;
//! - the machine, the toolchain, and which accelerated paths were active are
//!   printed with the results.
//!
//! Run with `cargo run --release -p blindplane-bench`.

#![allow(clippy::print_stdout, clippy::print_stderr)]
// Competitor crates are pinned at the versions being measured; their
// deprecation warnings are theirs, not ours.
#![allow(deprecated)]

use std::fmt::Write as _;
use std::hint::black_box;
use std::time::{Duration, Instant};

use blindplane_core::{Author, BatchItem, RecipientKeypair, open, seal, seal_batch};
use blindplane_crypto::aead::Suite;
use blindplane_crypto::argon2::{Argon2Params, argon2id};
use blindplane_crypto::hpke as bp_hpke;
use blindplane_crypto::montgomery::StaticSecret;
use blindplane_crypto::{Acceleration, Sha256, SigningKey, verify_strict};
use blindplane_wire::RecordContext;

const MIN_ROUND: Duration = Duration::from_millis(250);
const ROUNDS: usize = 5;

fn main() {
    let mut report = String::new();

    let acceleration = Acceleration::detect();
    println!("Blindplane benchmarks");
    println!("  cpu:          {}", cpu_name());
    println!("  cores:        {}", core_count());
    println!("  rustc:        {}", rustc_version());
    println!("  acceleration: {acceleration}");
    println!();

    let _ = writeln!(report, "# Benchmark results\n");
    let _ = writeln!(
        report,
        "Generated by `cargo run --release -p blindplane-bench`.\n"
    );
    let _ = writeln!(report, "| Property | Value |");
    let _ = writeln!(report, "|---|---|");
    let _ = writeln!(report, "| CPU | {} |", cpu_name());
    let _ = writeln!(report, "| Cores | {} |", core_count());
    let _ = writeln!(report, "| Toolchain | {} |", rustc_version());
    let _ = writeln!(report, "| Acceleration | `{acceleration}` |");
    let _ = writeln!(
        report,
        "| Method | best of {ROUNDS} rounds, each at least {} ms |\n",
        MIN_ROUND.as_millis()
    );

    bench_aead(&mut report);
    bench_hashing(&mut report);
    bench_asymmetric(&mut report);
    bench_hpke(&mut report);
    bench_password_hashing(&mut report);
    bench_end_to_end(&mut report);

    let path = std::path::Path::new("results/benchmarks.md");
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    match std::fs::write(path, &report) {
        Ok(()) => println!("\nwrote {}", path.display()),
        Err(error) => eprintln!("\ncould not write {}: {error}", path.display()),
    }
}

/// Time `body` for at least `MIN_ROUND`, returning operations per second.
fn measure(mut body: impl FnMut()) -> f64 {
    // Warm up caches, branch predictors and any lazily built table.
    for _ in 0..8 {
        body();
    }

    let mut best = 0.0_f64;
    for _ in 0..ROUNDS {
        let mut iterations = 0_u64;
        let start = Instant::now();
        loop {
            body();
            iterations += 1;
            if start.elapsed() >= MIN_ROUND {
                break;
            }
        }
        let rate = iterations as f64 / start.elapsed().as_secs_f64();
        best = best.max(rate);
    }
    best
}

fn throughput(bytes: usize, ops_per_second: f64) -> f64 {
    ops_per_second * bytes as f64 / 1e9
}

fn bench_aead(report: &mut String) {
    println!("== AEAD encryption (GB/s, higher is better) ==");
    let _ = writeln!(report, "## AEAD encryption\n");
    let _ = writeln!(
        report,
        "Throughput in GB/s over plaintext bytes, with 16 bytes of associated data.\n"
    );
    let _ = writeln!(report, "| Implementation | 1 KiB | 64 KiB | 1 MiB |");
    let _ = writeln!(report, "|---|---:|---:|---:|");

    let sizes = [1024_usize, 65_536, 1_048_576];
    let key = [0x42_u8; 32];
    let aad = [0x11_u8; 16];

    let mut rows: Vec<(String, Vec<f64>)> = Vec::new();

    // Ours, AES-256-GCM.
    if Suite::Aes256Gcm.is_available() {
        rows.push((
            "**Blindplane AES-256-GCM**".to_owned(),
            sizes
                .iter()
                .map(|size| {
                    let nonce = [0x24_u8; 12];
                    let mut buffer = vec![0_u8; *size];
                    throughput(
                        *size,
                        measure(|| {
                            let tag = Suite::Aes256Gcm
                                .seal_in_place(&key, &nonce, &aad, &mut buffer)
                                .expect("seal");
                            black_box(tag);
                        }),
                    )
                })
                .collect(),
        ));
    }

    // Ours, ChaCha20-Poly1305.
    rows.push((
        "**Blindplane ChaCha20-Poly1305**".to_owned(),
        sizes
            .iter()
            .map(|size| {
                let nonce = [0x24_u8; 12];
                let mut buffer = vec![0_u8; *size];
                throughput(
                    *size,
                    measure(|| {
                        let tag = Suite::ChaCha20Poly1305
                            .seal_in_place(&key, &nonce, &aad, &mut buffer)
                            .expect("seal");
                        black_box(tag);
                    }),
                )
            })
            .collect(),
    ));

    // Ours, XChaCha20-Poly1305.
    rows.push((
        "**Blindplane XChaCha20-Poly1305**".to_owned(),
        sizes
            .iter()
            .map(|size| {
                let nonce = [0x24_u8; 24];
                let mut buffer = vec![0_u8; *size];
                throughput(
                    *size,
                    measure(|| {
                        let tag = Suite::XChaCha20Poly1305
                            .seal_in_place(&key, &nonce, &aad, &mut buffer)
                            .expect("seal");
                        black_box(tag);
                    }),
                )
            })
            .collect(),
    ));

    // ring.
    rows.push((
        "ring AES-256-GCM".to_owned(),
        sizes
            .iter()
            .map(|size| {
                use ring::aead::{AES_256_GCM, Aad, LessSafeKey, Nonce, UnboundKey};
                let sealing = LessSafeKey::new(UnboundKey::new(&AES_256_GCM, &key).unwrap());
                let mut buffer = Vec::with_capacity(*size + 16);
                throughput(
                    *size,
                    measure(|| {
                        buffer.clear();
                        buffer.resize(*size, 0);
                        sealing
                            .seal_in_place_append_tag(
                                Nonce::assume_unique_for_key([0x24; 12]),
                                Aad::from(&aad),
                                &mut buffer,
                            )
                            .expect("seal");
                        black_box(&buffer);
                    }),
                )
            })
            .collect(),
    ));

    rows.push((
        "ring ChaCha20-Poly1305".to_owned(),
        sizes
            .iter()
            .map(|size| {
                use ring::aead::{Aad, CHACHA20_POLY1305, LessSafeKey, Nonce, UnboundKey};
                let sealing = LessSafeKey::new(UnboundKey::new(&CHACHA20_POLY1305, &key).unwrap());
                let mut buffer = Vec::with_capacity(*size + 16);
                throughput(
                    *size,
                    measure(|| {
                        buffer.clear();
                        buffer.resize(*size, 0);
                        sealing
                            .seal_in_place_append_tag(
                                Nonce::assume_unique_for_key([0x24; 12]),
                                Aad::from(&aad),
                                &mut buffer,
                            )
                            .expect("seal");
                        black_box(&buffer);
                    }),
                )
            })
            .collect(),
    ));

    // RustCrypto.
    rows.push((
        "RustCrypto aes-gcm".to_owned(),
        sizes
            .iter()
            .map(|size| {
                use aes_gcm::aead::{AeadInPlace, KeyInit};
                use aes_gcm::{Aes256Gcm, Key, Nonce};
                let cipher = Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(&key));
                let nonce = Nonce::from_slice(&[0x24_u8; 12]);
                let mut buffer = vec![0_u8; *size];
                throughput(
                    *size,
                    measure(|| {
                        let tag = cipher
                            .encrypt_in_place_detached(nonce, &aad, &mut buffer)
                            .expect("seal");
                        black_box(tag);
                    }),
                )
            })
            .collect(),
    ));

    rows.push((
        "RustCrypto chacha20poly1305".to_owned(),
        sizes
            .iter()
            .map(|size| {
                use chacha20poly1305::aead::{AeadInPlace, KeyInit};
                use chacha20poly1305::{ChaCha20Poly1305, Key, Nonce};
                let cipher = ChaCha20Poly1305::new(Key::from_slice(&key));
                let nonce = Nonce::from_slice(&[0x24_u8; 12]);
                let mut buffer = vec![0_u8; *size];
                throughput(
                    *size,
                    measure(|| {
                        let tag = cipher
                            .encrypt_in_place_detached(nonce, &aad, &mut buffer)
                            .expect("seal");
                        black_box(tag);
                    }),
                )
            })
            .collect(),
    ));

    for (name, values) in &rows {
        print!("  {name:34}");
        for value in values {
            print!("{value:9.2}");
        }
        println!();
        let _ = writeln!(
            report,
            "| {name} | {:.2} | {:.2} | {:.2} |",
            values[0], values[1], values[2]
        );
    }
    println!();
    let _ = writeln!(report);
}

fn bench_hashing(report: &mut String) {
    println!("== SHA-256 (GB/s, higher is better) ==");
    let _ = writeln!(report, "## SHA-256\n");
    let _ = writeln!(report, "| Implementation | 64 KiB |");
    let _ = writeln!(report, "|---|---:|");

    let size = 65_536;
    let data = vec![0x5a_u8; size];

    let ours = throughput(
        size,
        measure(|| {
            black_box(Sha256::digest(&data));
        }),
    );
    let rustcrypto = throughput(
        size,
        measure(|| {
            use sha2::Digest;
            black_box(sha2::Sha256::digest(&data));
        }),
    );
    let ring_rate = throughput(
        size,
        measure(|| {
            black_box(ring::digest::digest(&ring::digest::SHA256, &data));
        }),
    );

    for (name, value) in [
        ("**Blindplane SHA-256**", ours),
        ("RustCrypto sha2", rustcrypto),
        ("ring", ring_rate),
    ] {
        println!("  {name:34}{value:9.2}");
        let _ = writeln!(report, "| {name} | {value:.2} |");
    }
    println!();
    let _ = writeln!(report);
}

fn bench_asymmetric(report: &mut String) {
    println!("== Public key operations (ops/s, higher is better) ==");
    let _ = writeln!(report, "## Public-key operations\n");
    let _ = writeln!(report, "Operations per second on one core.\n");
    let _ = writeln!(report, "| Operation | Blindplane | Competitor | Ratio |");
    let _ = writeln!(report, "|---|---:|---:|---:|");

    // X25519.
    let ours_secret = StaticSecret::from_bytes([0x77_u8; 32]);
    let peer = StaticSecret::from_bytes([0x5d_u8; 32]).public_key();
    let our_x25519 = measure(|| {
        black_box(ours_secret.diffie_hellman(&peer));
    });
    let peer_secret = [0x5d_u8; 32];
    let dalek_x25519 = measure(|| {
        // One scalar multiplication, the same work our own call performs.
        black_box(x25519_dalek::x25519(peer_secret, ours_secret.public_key()));
    });

    // Ed25519 signing.
    let our_key = SigningKey::from_seed(&[0x9c_u8; 32]);
    let message = [0xab_u8; 256];
    let our_sign = measure(|| {
        black_box(our_key.sign(&message));
    });
    let dalek_key = ed25519_dalek::SigningKey::from_bytes(&[0x9c_u8; 32]);
    let dalek_sign = {
        use ed25519_dalek::Signer;
        measure(|| {
            black_box(dalek_key.sign(&message));
        })
    };

    // Ed25519 verification.
    let signature = our_key.sign(&message);
    let public_key = our_key.verifying_key();
    let our_verify = measure(|| {
        black_box(verify_strict(&public_key, &message, &signature).is_ok());
    });
    let dalek_verify = {
        use ed25519_dalek::Verifier;
        let verifying = dalek_key.verifying_key();
        let dalek_signature = ed25519_dalek::Signature::from_bytes(&signature);
        measure(|| {
            black_box(verifying.verify(&message, &dalek_signature).is_ok());
        })
    };

    for (name, ours, theirs, competitor) in [
        (
            "X25519 Diffie-Hellman",
            our_x25519,
            dalek_x25519,
            "x25519-dalek",
        ),
        ("Ed25519 sign", our_sign, dalek_sign, "ed25519-dalek"),
        (
            "Ed25519 verify (strict)",
            our_verify,
            dalek_verify,
            "ed25519-dalek",
        ),
    ] {
        println!("  {name:28}{ours:12.0}{theirs:12.0}   ({competitor})");
        let _ = writeln!(
            report,
            "| {name} | {ours:.0} | {theirs:.0} ({competitor}) | {:.2}x |",
            ours / theirs
        );
    }
    println!();
    let _ = writeln!(report);
}

fn bench_hpke(report: &mut String) {
    println!("== HPKE seal, ChaCha20-Poly1305 (ops/s) ==");
    let _ = writeln!(report, "## HPKE (RFC 9180) single-shot seal\n");
    let _ = writeln!(report, "| Implementation | ops/s |");
    let _ = writeln!(report, "|---|---:|");

    let recipient = StaticSecret::from_bytes([0x31_u8; 32]);
    let recipient_public = recipient.public_key();
    let payload = [0x7e_u8; 32];

    let ours = measure(|| {
        let result = bp_hpke::seal(
            Suite::ChaCha20Poly1305,
            &recipient_public,
            b"info",
            b"aad",
            &payload,
        );
        black_box(result.is_ok());
    });

    let theirs = {
        use ::hpke::{
            Deserializable, Kem as KemTrait, OpModeS, aead::ChaCha20Poly1305, kdf::HkdfSha256,
            kem::X25519HkdfSha256, setup_sender,
        };
        type Kem = X25519HkdfSha256;
        let public = <Kem as KemTrait>::PublicKey::from_bytes(&recipient_public).unwrap();
        measure(|| {
            let (encapsulated, mut sender) =
                setup_sender::<ChaCha20Poly1305, HkdfSha256, Kem>(&OpModeS::Base, &public, b"info")
                    .unwrap();
            let ciphertext = sender.seal(&payload, b"aad").unwrap();
            black_box((encapsulated, ciphertext));
        })
    };

    for (name, value) in [("**Blindplane HPKE**", ours), ("hpke crate", theirs)] {
        println!("  {name:34}{value:12.0}");
        let _ = writeln!(report, "| {name} | {value:.0} |");
    }
    println!();
    let _ = writeln!(report);
}

fn bench_password_hashing(report: &mut String) {
    println!("== Argon2id, 64 MiB x 3 passes (ops/s, lower bound is the point) ==");
    let _ = writeln!(report, "## Argon2id, m=64 MiB, t=3, p=1\n");
    let _ = writeln!(
        report,
        "Password hashing is meant to be slow. Parity with the reference implementation is the goal, not speed.\n"
    );
    let _ = writeln!(report, "| Implementation | ops/s | ms per hash |");
    let _ = writeln!(report, "|---|---:|---:|");

    let params = Argon2Params {
        memory_kib: 65_536,
        passes: 3,
        output_len: 32,
    };
    let ours = measure(|| {
        black_box(argon2id(b"correct horse battery staple", b"blindplane-salt!", params).unwrap());
    });

    let theirs = {
        use argon2::{Algorithm, Argon2, Params, Version};
        let reference = Argon2::new(
            Algorithm::Argon2id,
            Version::V0x13,
            Params::new(65_536, 3, 1, Some(32)).unwrap(),
        );
        measure(|| {
            let mut out = [0_u8; 32];
            reference
                .hash_password_into(
                    b"correct horse battery staple",
                    b"blindplane-salt!",
                    &mut out,
                )
                .unwrap();
            black_box(out);
        })
    };

    for (name, value) in [("**Blindplane Argon2id**", ours), ("argon2 crate", theirs)] {
        println!("  {name:34}{value:12.1}{:12.1}", 1000.0 / value);
        let _ = writeln!(report, "| {name} | {value:.1} | {:.1} |", 1000.0 / value);
    }
    println!();
    let _ = writeln!(report);
}

fn bench_end_to_end(report: &mut String) {
    println!("== End-to-end records (ops/s) ==");
    let _ = writeln!(report, "## End-to-end sealed records\n");
    let _ = writeln!(
        report,
        "A full record: fresh object secret, payload AEAD, one HPKE envelope per recipient, key commitment, Ed25519 signature and canonical encoding.\n"
    );
    let _ = writeln!(report, "| Operation | ops/s |");
    let _ = writeln!(report, "|---|---:|");

    let author = Author::generate().unwrap();
    let alice = RecipientKeypair::generate("alice", 1).unwrap();
    let suite = Suite::fastest_available();
    let payload = vec![0x33_u8; 4096];
    let context = RecordContext {
        tenant: "acme".into(),
        object_id: "object-1".into(),
        field: "notes".into(),
        epoch: 1,
        version: 1,
        schema_version: 1,
    };

    let seal_rate = measure(|| {
        let record = seal(
            &author,
            context.clone(),
            &payload,
            &[alice.recipient()],
            vec![],
            suite,
        )
        .unwrap();
        black_box(record);
    });

    let record = seal(
        &author,
        context.clone(),
        &payload,
        &[alice.recipient()],
        vec![],
        suite,
    )
    .unwrap();
    let signer = author.public_key();
    let open_rate = measure(|| {
        black_box(open(&record, &alice, signer).unwrap());
    });

    let three: Vec<_> = (0..3)
        .map(|i| RecipientKeypair::generate(format!("user-{i}"), 1).unwrap())
        .collect();
    let three_recipients: Vec<_> = three.iter().map(RecipientKeypair::recipient).collect();
    let seal_three = measure(|| {
        let record = seal(
            &author,
            context.clone(),
            &payload,
            &three_recipients,
            vec![],
            suite,
        )
        .unwrap();
        black_box(record);
    });

    // Batch sealing across every core.
    let batch: Vec<BatchItem> = (0..256)
        .map(|i| BatchItem {
            context: RecordContext {
                object_id: format!("object-{i}"),
                ..context.clone()
            },
            plaintext: payload.clone(),
            recipients: vec![alice.recipient()],
            indexes: vec![],
        })
        .collect();
    let batch_rate = measure(|| {
        let results = seal_batch(&author, &batch, suite);
        black_box(results.len());
    }) * batch.len() as f64;

    for (name, value) in [
        ("seal, 4 KiB, 1 recipient", seal_rate),
        ("open, 4 KiB, 1 recipient", open_rate),
        ("seal, 4 KiB, 3 recipients", seal_three),
        ("seal batch, all cores (records/s)", batch_rate),
    ] {
        println!("  {name:38}{value:12.0}");
        let _ = writeln!(report, "| {name} | {value:.0} |");
    }
    println!();
    let _ = writeln!(
        report,
        "\nBatch sealing scales across cores: each record has its own object secret, so nothing is shared and nothing needs locking.\n"
    );
}

fn cpu_name() -> String {
    std::process::Command::new("sysctl")
        .args(["-n", "machdep.cpu.brand_string"])
        .output()
        .ok()
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
        .unwrap_or_else(|| std::env::consts::ARCH.to_owned())
}

fn core_count() -> String {
    std::thread::available_parallelism()
        .map_or_else(|_| "unknown".to_owned(), |count| count.to_string())
}

fn rustc_version() -> String {
    std::process::Command::new("rustc")
        .arg("-V")
        .output()
        .ok()
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map_or_else(|| "unknown".to_owned(), |value| value.trim().to_owned())
}
