//! Benchmarks comparing Blindplane's cryptographic core against established
//! implementations on the same machine, in the same process, on the same data.
//!
//! Methodology, so the numbers mean something:
//!
//! - each measurement runs for at least 250 ms, and the reported figure is the
//!   median of five such rounds — the median, unlike a best-of, cannot be
//!   inflated by one lucky scheduling window;
//! - every implementation processes identical inputs and its output is checked,
//!   so a fast wrong answer cannot win;
//! - throughput counts plaintext bytes, not ciphertext, so the tag does not
//!   inflate anyone's number;
//! - the machine, the toolchain, and which accelerated paths were active are
//!   printed with the results.
//!
//! Run with `cargo run --release -p blindplane-bench`.

#![allow(clippy::print_stdout, clippy::print_stderr)]
// Competitor crates are pinned at the versions being measured; their
// deprecation warnings are theirs, not ours.
#![allow(deprecated)]

mod aead;
mod asymmetric;
mod hashing;
mod protocol;
mod records;

use std::fmt::Write as _;
use std::time::{Duration, Instant};

use blindplane_crypto::Acceleration;

pub(crate) const MIN_ROUND: Duration = Duration::from_millis(250);
pub(crate) const ROUNDS: usize = 5;

fn main() {
    let mut report = String::new();

    let acceleration = Acceleration::detect();
    println!("Blindplane benchmarks");
    println!("  cpu:          {}", cpu_name());
    println!("  cores:        {}", core_count());
    println!("  rustc:        {}", rustc_version());
    println!("  acceleration: {acceleration}");
    println!();

    let _ = writeln!(report, "# Benchmark results\n");
    let _ = writeln!(
        report,
        "Generated by `cargo run --release -p blindplane-bench`.\n"
    );
    let _ = writeln!(report, "| Property | Value |");
    let _ = writeln!(report, "|---|---|");
    let _ = writeln!(report, "| CPU | {} |", cpu_name());
    let _ = writeln!(report, "| Cores | {} |", core_count());
    let _ = writeln!(report, "| Toolchain | {} |", rustc_version());
    let _ = writeln!(report, "| Acceleration | `{acceleration}` |");
    let _ = writeln!(
        report,
        "| Method | median of {ROUNDS} rounds, each at least {} ms |\n",
        MIN_ROUND.as_millis()
    );

    aead::bench_aead(&mut report);
    hashing::bench_hashing(&mut report);
    asymmetric::bench_asymmetric(&mut report);
    protocol::bench_hpke(&mut report);
    protocol::bench_password_hashing(&mut report);
    records::bench_end_to_end(&mut report);

    let path = std::path::Path::new("results/benchmarks.md");
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    match std::fs::write(path, &report) {
        Ok(()) => println!("\nwrote {}", path.display()),
        Err(error) => eprintln!("\ncould not write {}: {error}", path.display()),
    }
}

/// Time `body` for at least `MIN_ROUND`, returning the median rate in
/// operations per second across `ROUNDS` rounds.
pub(crate) fn measure(mut body: impl FnMut()) -> f64 {
    // Warm up caches, branch predictors and any lazily built table.
    for _ in 0..8 {
        body();
    }

    let mut rates = [0.0_f64; ROUNDS];
    for rate in &mut rates {
        let mut iterations = 0_u64;
        let start = Instant::now();
        loop {
            body();
            iterations += 1;
            if start.elapsed() >= MIN_ROUND {
                break;
            }
        }
        *rate = iterations as f64 / start.elapsed().as_secs_f64();
    }
    rates.sort_unstable_by(f64::total_cmp);
    rates[ROUNDS / 2]
}

pub(crate) fn throughput(bytes: usize, ops_per_second: f64) -> f64 {
    ops_per_second * bytes as f64 / 1e9
}

fn cpu_name() -> String {
    std::process::Command::new("sysctl")
        .args(["-n", "machdep.cpu.brand_string"])
        .output()
        .ok()
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
        .unwrap_or_else(|| std::env::consts::ARCH.to_owned())
}

fn core_count() -> String {
    std::thread::available_parallelism()
        .map_or_else(|_| "unknown".to_owned(), |count| count.to_string())
}

fn rustc_version() -> String {
    std::process::Command::new("rustc")
        .arg("-V")
        .output()
        .ok()
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map_or_else(|| "unknown".to_owned(), |value| value.trim().to_owned())
}
